/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tugas.praktikum;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        A classUnderTest = new A();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
